Sedelnikov grigorii
eugene-okulik/socratin pull request #4
Opened 2024-03-01 17:50 UTC by grigorijobucenie

Сделал задание 4

2024-03-02 11:39 UTC, eugene-okulik requested changes

2024-03-02 11:39 UTC, eugene-okulik commented on homework/grigorii_sedelnikov/4/my_dict (1).py
> +    my_new_dict["i am a tuple"] = 777
В задании было

> добавьте элемент с ключом ('i am a tuple',) и любым значением

А ты выполнил так, как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

Это название ключа подсказывает чем он должен быть

2024-03-02 16:55 UTC, grigorijobucenie commented
Исправил ошибку

2024-03-03 07:57 UTC, eugene-okulik requested changes

2024-03-03 07:57 UTC, eugene-okulik commented on homework/grigorii_sedelnikov/4/my_dict (2).py
> +    my_new_dict["('i am a tuple',)"] = (7, 7, 7)
Сейчас ключом является строка, но сама эта строка говорит "я есть кортеж". Идея в том, что ключом будет кортеж с одним элементом, который пишется прямо ровно так, как написано в задании

2024-03-03 11:39 UTC, eugene-okulik approved these changes

2024-03-03 11:39 UTC, merged